version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_e_commerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: naresh@123
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: naresh
      MYSQL_PASSWORD: naresh@123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper_e_commerce
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka_e_commerce
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend-net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_e_commerce
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-no-password.xml:/etc/clickhouse-server/users.d/disable-password.xml
    networks:
      - backend-net

volumes:
  clickhouse-data:

networks:
  backend-net:
  mysql-data:
